" 기본 설정
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

" 기본 구문 강조 및 파일타입 설정
syntax on
filetype plugin indent on

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry

" Java 구문 강조 설정
let java_highlight_all = 1
let java_highlight_debug = 1
let java_highlight_functions = 1
let java_highlight_java_lang_ids = 1

" 기본 설정
set matchpairs+=a:b
set hlsearch
set number
set mouse=a
hi LineNr cterm=NONE ctermbg=darkgrey ctermfg=lightgrey guifg=grey guibg=darkgrey
hi CursorLineNr cterm=bold ctermfg=yellow guifg=yellow
set autoindent
set scrolloff=2
set wildmode=longest,list
set ts=4
set sts=4
set sw=1
set autowrite
set autoread
set cindent
set bs=eol,start,indent
set history=256
set laststatus=2
set paste
set shiftwidth=4
set showmatch
set smartcase
set smarttab
set smartindent
set softtabstop=4
set tabstop=4
set ruler
set incsearch
set completeopt=menuone,popup,noselect,fuzzy

" 키 매핑 설정
map <F12> :noh <CR>
let mapleader = "\\"
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <leader>f :NERDTreeFind<CR>

" 분할된 창 사이를 쉽게 이동
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" 버퍼 간 이동
nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>

" 현재 줄을 위아래로 이동 (warp에서는 동작하지 않으므로 임시 주석, 24.12.13)
" nnoremap <A-j> :m .+1<CR>==
" nnoremap <A-k> :m .-2<CR>==
nnoremap <S-j> :m .+1<CR>==
nnoremap <S-k> :m .-2<CR>==

" fzf.vim 활용
nnoremap <C-p> :Files<CR>
nnoremap <leader>/ :BLines<CR>
nnoremap <leader>rg :Rg<CR>

" 자동 명령어 설정
" 저장 시 자동으로 trailing whitespace 제거
autocmd BufWritePre * %s/\s\+$//e

" 파일 형식별 설정
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4
autocmd FileType javascript setlocal expandtab shiftwidth=2 softtabstop=2
autocmd FileType java setlocal expandtab shiftwidth=4 softtabstop=4
" Java 특수 설정
autocmd FileType java syntax clear
autocmd FileType java runtime! syntax/java.vim
autocmd FileType java let b:ale_linters = ['javac']
autocmd FileType java let b:ale_fixers = ['google_java_format']

" 플러그인 설정
call plug#begin('~/.vim/plugged')

" 파일 탐색
Plug 'preservim/nerdtree', { 'on': ['NERDTreeToggle', 'NERDTreeFind'] }
Plug 'Xuyuanp/nerdtree-git-plugin'

" 파일 검색
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" 상태 표시줄
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" 자동 괄호 완성
Plug 'jiangmiao/auto-pairs'

" 다중 커서 지원
Plug 'terryma/vim-multiple-cursors'

" 코드 자동완성
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Java 전용 구문 강조 플러그인
Plug 'uiiaoo/java-syntax.vim'

" 파일 내 빠른 이동
Plug 'easymotion/vim-easymotion', { 'on': ['<Plug>(easymotion-s)', '<Plug>(easymotion-bd-w)'] }

" 버퍼 관리
Plug 'jeetsukumaran/vim-buffergator'

" 주석 처리
Plug 'tpope/vim-commentary'

" Git 통합
Plug 'tpope/vim-fugitive', { 'on': ['Git', 'Gstatus', 'Gcommit'] }

" 문자 둘러싸기 편집
Plug 'tpope/vim-surround'

" 비동기 린터 및 문법 검사
Plug 'dense-analysis/ale'

" 테마
Plug 'morhetz/gruvbox'

call plug#end()

" COC 설정
let g:coc_global_extensions = ['coc-java', 'coc-json']
let g:coc_start_at_startup = 1

" 테마 설정
colorscheme gruvbox

